config/routes.rb
Cad::Application.routes.draw do
  root :to => "events#index"
  #resources :mobiles
  resources :events
  resources :mobiles
  match "/mobile" => "mobiles#index" 
  match "/mobile/:id"  => "mobiles#show"
  match "/mobilesig" => "mobiles#sig", :as => :mobilesig
  match "/admin" => "events#admin"
  match "/admin/new" => "events#new"
  match "/admin/:id/edit" => "events#edit"
end

app/models/event.rb
class Event < ActiveRecord::Base

	# paperclip
	has_attached_file :eventflyer, 
		:styles => { :medium => "300x200#",
		:thumb => "220x126#",
		:mobile => "80x80#"	}
		
	scope :currentevents, lambda {where("event_date > ?" , Time.now.beginning_of_day).order("event_date ASC") }
	
	validates :event_title, :event_description, :event_location, :event_dateend, :event_date, :presence => true
	validate :date_logical	
	
	def date_logical
		errors.add(:event_dateend, "The end of the event's date/time must be greater than the start of the event's date/time") if
		!event_dateend.blank? and event_dateend < event_date
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper :all
  protect_from_forgery
  
  private
  
    def mobile_device?
      user_agent = request.user_agent
      user_agent =~ /Mobile|webOS/
    end
    
    helper_method :mobile_device?
    
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password|
        user_name == 'cad' && password == '1q2w3e4r!'
      end
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate, :except => [:index, :show]

	def index
		@event = Event.currentevents
		@eventdate = Event.currentevents.group_by{ |e| e.event_date.beginning_of_day } 	
		if mobile_device?
			redirect_to :controller => "mobiles", :action => "index"
		end
	end
	
	# show all events for the admin
	def admin
		@event = Event.order("event_date ASC")
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(params[:event])
		respond_to do |format|
			if @event.save
				format.html { redirect_to(new_event_path, :notice => 'Event was successfully created.') }
			else
				format.html { render :action => "new" }
			end
		end
	end
	
	def edit
		@event = Event.find(params[:id])
	end
	
	def update
		@event = Event.find(params[:id])
		respond_to do |format|
			if @event.update_attributes(params[:event])
				format.html { redirect_to(admin_url, :notice => 'Event was successfully updated.') }
			else
				format.html { render :action => "edit" }
			end
		end
	end
	
	def show
	    @event = Event.find(params[:id])
	end
	
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		respond_to do |format|
		  format.html { redirect_to(admin_url) }
		end
	end

	end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController

	layout "mobile"
	
	def index
		@mobile = Event.currentevents
		@event_by_day = Event.currentevents.group_by{ |m| m.event_date.beginning_of_day }
	end
	
	def show
		@mobile = Event.find(params[:id])	
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<div class="grid_12">
	<%= form_for(@event, :html => { :multipart => true }) do |f| %>  
	  <% if @event.errors.any? %>
	  <div id="errorExplanation">
		<h3><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
		<ul>
		<% @event.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
		<% end %>
	  <div class="field">
		<%= f.label(:event_title, 'Event Title', :class => 'main') %><br />
		<%= f.text_field :event_title, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:event_location, 'Event Location', :class => 'main') %><br />
		<%= f.text_field :event_location, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:event_date, 'Start Date and Time', :class => 'main') %><br />
		<%= f.text_field :event_date, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:event_dateend, 'End Date and Time', :class => 'main') %><br />
		<%= f.text_field :event_dateend, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:event_description, 'Event Description', :class => 'main') %><br />
		<%= f.text_area :event_description, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:event_sponsers, 'Event Sponsors', :class => 'main') %><br />
		<%= f.text_field :event_sponsers, :class => 'textbox' %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.label(:eventflyer, 'Do you have a thumbnail', :class => 'main') %><br />
		<%= f.file_field :eventflyer %>
	  </div>
	  <br />
	  <div class="field">
		<%= f.submit 'Save', :class => 'btn', :id => 'emphasis' %>
	  </div>
	<% end %>
</div>

app/views/events/admin.html.erb
<div class="grid_12">
	<h1>Admin</h1>
	<% if !notice.blank? %><p class="notice"><%= notice %></p><% end %>
	<p class="readmore"><%= link_to "New Event", new_event_path %></p>
	<table width="940">
		<thead>
			<tr>
				<th></th>
				<th>Event</th>
				<th>Location</th>
				<th>Start Date/Time</th>
				<th>Options</th>
			</tr>
		</thead>
		<% @event.each do |e| %>
		<tbody>
			<tr>
				<td align="center" valign="middle"><% if !e.eventflyer_file_name.nil? %> <%= image_tag e.eventflyer.url(:mobile), :alt => e.event_title %><% else %><%= image_tag('ad80.png') %><% end %></td>
				<td><b><%= e.event_title %></b></td>
				<td><%= e.event_location %>
				<td><%= e.event_date.strftime("%b %d at %I:%M %p") %></td>
				<td>
					<%= link_to 'Edit/Show', edit_event_path(e) %><br />
					<%= link_to 'Delete', e, :confirm => 'Are you sure you want to delete this? If so, all event information will be lost.', :method => :delete %></td>				
				</td>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>

app/views/events/edit.html.erb
<div class="grid_12">
	<h2>Edit event</h2>
	<%= render 'form' %>
</div>	

app/views/events/index.html.erb
<!-- Logo -->
<div class="grid_4 logo">
	<%= link_to image_tag('logo.png'), :action => 'index'	%>
</div>
<!--  END Logo -->
						
<!-- Events -->
<div class="grid_12"><h1>Events</h1></div>
<div class="grid_12 datefilter">
	<ul id="portfolio-filter">
		<li><a href="#all" class="all">Full Schedule</a></li>
		<% @eventdate.each do |e, events| %>
			<li><a href="#<%= e.strftime("%m%d") %>" rel="<%= e.strftime("%m%d") %>"><%= e.strftime("%A, %b %d") %></a></li>
		<% end %>
	</ul>	
</div>
<ul id="portfolio-list">
	<% @event.each do |event| %>
	<li class="grid_4 event <%= event.event_date.strftime("%m%d") %>">
		<div class="eventimg">			
			<% if Time.now > event.event_dateend.to_time %>
				<div class="expired">Event Finished</div>
			<% end %>	
			<% if !event.eventflyer_file_name.nil? %>
				<%= link_to (image_tag event.eventflyer.url(:medium), :alt => event.event_title), event %>
			<% else %>
				<%= link_to image_tag('ad300.png'), event %>
			<% end %>	
		</div>
		<div class="eventtext">
			<h2><%=link_to event.event_title, event %></h2>
			<p class="eventdate">
				<%= event.event_date.strftime("%b %d at %I:%M %p") %><br />
				<span><%= event.event_location %></span>
			</p>
			<p class="desc"><%= truncate(event.event_description, :length => 194) %></p>
			<p class="readmore"><%= link_to 'Read More', event %></p>
		</div>
	</li>
	<% end %>
</ul>	
<!-- END Events -->

		

app/views/events/new.html.erb
<div class="grid_12">
	<%= image_tag('logo_mobile.png') %>
	<h2>Add a new event</h2>
	<% if !notice.blank? %><p class="notice"><%= notice %></p><% end %>
	<%= render 'form' %>
</div>	

app/views/events/show.html.erb
<!-- Logo -->
<div class="grid_4 logo">
	<%=image_tag('logo.png') %>
</div>
<!--  END Logo -->

<div class="grid_12 showcontent">
	<h2><%= @event.event_title %> - <span><%= @event.event_date.strftime("%b %d at %I:%M %p") %></span> - <%= @event.event_location %></h2>
	<div class="grid_8 alpha">
		<p><%= @event.event_description %></p>
		<p><b>Event Sponsor(s)</b> <%= @event.event_sponsers %></p>
		<p class="readmore2"><%= link_to 'Back', events_path %></p>
	</div>
	<div class="grid_4 omega">
			<% if !@event.eventflyer_file_name.nil? %>
				<%= image_tag @event.eventflyer.url(:original), :width => "300" %>
			<% else %>
				<%= image_tag('ad300.png') %>
			<% end %>				
	</div>
</div>
			
			
			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Carolina After Dark</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :all %>
	<%= csrf_meta_tag %>
</head>
	<body>
		<canvas id="pixie"></canvas>
		<div class="container_12">
			<%= yield %>
			<div class="grid_12 footer">

				<div class="grid_4 links alpha">
					<h3>For more information contact</h3>
					<p><b>Sarah Morgan</b><br />
					<a href="mailto:morgans@mailbox.sc.edu">morgans@mailbox.sc.edu</a><br />
					Russell House University Union, Suite 227<br />
					Phone (803) 777-7130</p>		
				</div>	
				<div class="grid_5">
						<h3 class="twitter">Twitter</h3>
						<div class="tweet"></div>
				</div>
				<div class="grid_2 tag omega">
					<%= link_to image_tag('footer_logo.png'), 'http://www.sa.sc.edu/stlife' %>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Carolina After Dark</title>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" />
	<script src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.js"></script>
	<%= csrf_meta_tag %>
	<style type="text/css">
		body {
			background:#fff;
		}
		.ui-bar-b {
			background: #660000;
			background: -moz-linear-gradient(top, #660000 0%, #90122a 100%);
			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#660000), color-stop(100%,#90122a));
			background: -webkit-linear-gradient(top, #660000 0%,#90122a 100%);
			background: -o-linear-gradient(top, #660000 0%,#90122a 100%);
			background: -ms-linear-gradient(top, #660000 0%,#90122a 100%);
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#C90000', endColorstr='#90122a',GradientType=0 );
			background: linear-gradient(top, #660000 0%,#90122a 100%);
			border:1px solid #90122a;
		}
		.ui-btn-inner {
			border: #;
		}
	</style>
</head>
<body>
	<div data-role="page">
		<%= yield %>
	</div>
</body>
</html>

app/views/mobiles/index.html.erb
<div data-role="header">
  <h1>UNIVERSITY OF SC</h1>
</div>
	<div style="height:100%; width:100%; background-color:#000; text-align:center;">
		<%= image_tag('cad_mobile.png') %>
	</div>
<div data-role="content">
	<ul data-role="listview">
	<% @event_by_day.each do |m, events| %>
				<li data-role="list-divider"><%= m.strftime("%b %d") %></li>		
			<% for event in events %>
				<li>
					<%= link_to(mobile_path(event)) do %>
						<% if !event.eventflyer_file_name.nil? %>
							<%= image_tag event.eventflyer.url(:mobile), :alt => event.event_title %>
						<% else %>
							<%= image_tag('ad80.png') %>
						<% end %>	
						<h3 class="ui-li-heading"><%= event.event_title %></h3>
						<p class="ui-li-desc"><%= event.event_date.strftime("%I:%M %p") %> - <%= event.event_location %></p>
					<% end %>
				</li>		
			<% end %>
	<% end %>
	</ul>

</div>

app/views/mobiles/show.html.erb
<div data-role="header">
  <h1>CAD | <%= @mobile.event_title %></h1>
   <%= link_to 'Home', mobiles_path, "class" => "ui-btn-left" %>
</div>


<div data-role="content"
	<% if !@mobile.eventflyer_file_name.nil? %>
		<%= image_tag @mobile.eventflyer.url(:thumb), :alt => @mobile.event_title %>
	<% else %>
		<%= image_tag('ad220.png') %>
	<% end %>	
	<h4><%= @mobile.event_date.strftime("%b %d at %I:%M %p") %><br /><%= @mobile.event_location %></h4>
	<p><%= @mobile.event_description %></p>
	<p><%= @mobile.event_sponsers %></p>
</div>

app/views/mobiles/sig.html.erb
<div data-role="header">
  <h1>Signature Events</h1>
</div>

<div data-role="content">
	<ul data-role="listview" >
		<% @event_by_day.each do |m, events| %>
				<li data-role="list-divider" data-theme="a"><%= m.strftime("%b %d") %></li>		
			<% for event in events %>
				<li>
					<%= link_to(mobile_path(event)) do %>
						<% if !event.eventflyer_file_name.nil? %>
							<%= image_tag event.eventflyer.url(:mobile), :alt => event.event_title %>
						<% else %>
							<%= image_tag('cw80.png') %>
						<% end %>	
						<h3 class="ui-li-heading"><%= event.event_title %></h3>
						<p class="ui-li-desc"><%= event.event_date.strftime("%I:%M %p") %> - <%= event.event_location %></p>
					<% end %>
				</li>		
			<% end %>
		<% end %>
	</ul>
</div>